### ISSUE TITLE
نسخه SCSS

### ISSUE THREAD

**Issue by pmpr-ir** [mRizvandi/AryaBootstrap#2]
<span dir=rtl>سلام به شما. آیا این کتابخانه نسخه قابل ویرایش ندارد؟</span>

**Comment by mRizvandi** [comment]
سلام
ضمن تشکر از شما بابت توجه تان به این کتابخانه، متاسفانه با توجه به اینکه کتابخانه از روی نسخه کامپایل شده CSS تهیه شده، امکان تهیه نسخه SCSS میسر نیست.
